Repository AY2425S2-CS2103-F10-1/tp, pull requests merged in 2025-03, with the labels that each got.

#63 Update top navbar & index
  docs/index.md
Labels: type.Task

#70 Add common terms to glossary list
  docs/DeveloperGuide.md
Labels: documentation

#73 Update developer guide.md
  docs/DeveloperGuide.md
Labels: documentation

#72 Add UC02 and UC06
  docs/DeveloperGuide.md
Labels: documentation

#79 Target User, Value Proposition and MVP User Stories
  docs/DeveloperGuide.md
Labels: documentation

#71 Add UC01, UC03, UC04, UC05
  docs/DeveloperGuide.md
Labels: documentation

#80 Add Ui mockup image
  docs/images/Ui.png
Labels: documentation

#102 Amend add command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/exceptions/DuplicatePersonException.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement

#105 Resolve minor style issues in Developer Guide
  docs/DeveloperGuide.md
Labels: documentation, severity.VeryLow

#103 Modify point 2 of NFRs
  docs/DeveloperGuide.md
Labels: documentation

#124 Enhance tag
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UnTagCommand.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/logic/parser/UnTagCommandParser.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Enhancement

#123 Fix save file accumulation
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/SaveCommand.java
  src/main/java/seedu/address/logic/commands/enumeration/SavingCommandTypes.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/test/java/seedu/address/commons/util/FileUtilTest.java
Labels: type.Enhancement, type.bug, priority.High, severity.Medium

#135 Update footer status
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/SaveCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
Labels: type.Enhancement, priority.Low

#137 Update testcases for status footer
  src/main/java/seedu/address/logic/commands/SaveCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: type.Enhancement, priority.Low

#148 Add Tag and UnTag to User Guide
  docs/UserGuide.md
  docs/images/tagAdded.png
  docs/images/tagRemoved.png
Labels: documentation

#155 Update help screenshot
  docs/images/helpMessage.png
Labels: documentation, severity.VeryLow

#159 Update build.gradle
  build.gradle
Labels: severity.Low

#161 Update userguide exit
  docs/UserGuide.md
Labels: severity.VeryLow

#162 Update ArtHive version to 1.3.0
  src/main/java/seedu/address/MainApp.java
Labels: type.bug, severity.VeryLow

#163 Update documentation images
  docs/images/find87438807_99272758Result.png
  docs/images/findAlexDavidResult.png
Labels: documentation, priority.Medium, severity.VeryLow

#178 Add Project Sub-functionality to TagCommand & UnTagCommand
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UnTagCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/logic/parser/UnTagCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Project.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: priority.High

#183 Resolve Project save bugs
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UnTagCommand.java
Labels: type.bug, priority.High

#189 Enhance Untag Command & Resolve failing test cases
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/UnTagCommand.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/commands/UnTagCommandTest.java
Labels: priority.Medium

#191 Fix project load issue
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
Labels: type.bug, priority.High

#188 Update developer guide preferred contact
  docs/DeveloperGuide.md
Labels: documentation

#190 Update user guide to add in switch contact command
  docs/UserGuide.md
  docs/images/switchContactJohn.png
Labels: documentation

#195 Update UI to show project attributes
  src/main/java/seedu/address/logic/commands/SwitchContactCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UnTagCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Project.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/Projects.fxml
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#197 Add snapshot feature
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/commands/SnapshotCommand.java
  src/main/java/seedu/address/logic/commands/enumeration/SavingCommandTypes.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/storage/JsonSnapshotStorage.java
  src/main/java/seedu/address/storage/SnapshotStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
Labels: type.Enhancement

#201 Fix tests failing and save project attributes
  src/main/java/seedu/address/model/tag/Project.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.High

#204 Modify Edit Command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Enhancement, priority.Medium

#199 Add snapshot to docs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/snapshot.png
Labels: documentation

#212 Update Model Class Diagram
  docs/diagrams/ModelClassDiagram.puml
Labels: documentation

#207 Update User Guide for Tag/UnTag to consider Project functionality
  docs/UserGuide.md
Labels: documentation

#217 Modify LogicClassDiagram uml
  docs/diagrams/LogicClassDiagram.puml
Labels: documentation

#234 Improve codecov for Tag/Untag Commands & Tag Model
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UnTagCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/commands/UnTagCommandTest.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnTagCommandParserTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#240 Overzealous Command Input Validation for switchContact
  src/main/java/seedu/address/logic/commands/SwitchContactCommand.java
  src/main/java/seedu/address/logic/commands/enumeration/SavingCommandTypes.java
Labels: priority.Medium, alpha-bug, type.FeatureFlaw

#243 Make all commands case-insensitive for ease of use
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: priority.Medium, alpha-bug, type.FeatureFlaw

#233 Enhance Project Class
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/Project.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/model/tag/ProjectTest.java
Labels: priority.Medium, alpha-bug, type.FeatureFlaw

#236 Fix I/O edge cases, remove dead code, and redundant code
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/commands/SaveCommand.java
  src/main/java/seedu/address/logic/commands/SnapshotCommand.java
  src/main/java/seedu/address/logic/commands/enumeration/SavingCommandTypes.java
Labels: type.FunctionalityBug, priority.Medium, alpha-bug

#247 Error message for Email in Add Command is too long
  src/main/java/seedu/address/model/person/Email.java
Labels: severity.Low, alpha-bug, type.FeatureFlaw

#264 Update dev guide
  docs/DeveloperGuide.md
Labels: documentation, severity.Low, alpha-bug, type.DocumentationBug

#251 Reorder User Guide Sections for "Editing Data File"
  docs/UserGuide.md
Labels: documentation, alpha-bug, type.DocumentationBug

#262 Add "domain label", "domain" into the glossary list
  docs/DeveloperGuide.md
Labels: documentation, alpha-bug

#265 Update user guide
  docs/UserGuide.md
Labels: documentation, severity.Low, alpha-bug, type.DocumentationBug
