Repository AY2425S2-CS2103-F10-1/tp, pull requests merged in 2025-04, with the labels that each got.

#269 Add Images to User Guide, and rectify Find command issues
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addContactResult.jpg
  docs/images/addContactResult.png
  docs/images/clearafter.png
  docs/images/clearbefore.png
  docs/images/editafter.png
  docs/images/editbefore.png
Labels: documentation, priority.Medium, alpha-bug

#270 Fix formatting in Developer Guide for SwitchContact use case
  docs/DeveloperGuide.md
Labels: alpha-bug, type.DocumentationBug

#273 Update project prefix
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SetStatusCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: documentation, severity.Medium

#278 Use case should not include UI details in Developer Guide
  docs/DeveloperGuide.md
Labels: alpha-bug, type.DocumentationBug

#276 Update User Guide to add all necessary constraints of prefix into all the command
  docs/UserGuide.md
Labels: alpha-bug, type.DocumentationBug

#255 Use of non-alphanumeric characters in Name for Add command
  src/main/java/seedu/address/logic/commands/enumeration/PrefixEnum.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: severity.Medium, alpha-bug

#284 Update storage component diagram in dg
  docs/diagrams/StorageClassDiagram.puml
Labels: documentation

#277 Update user guide to include setstatus
  docs/UserGuide.md
  docs/images/setstatusPaymentDeadline.png
  docs/images/setstatusProgress.png
  docs/images/setstatusSampleState.png
  src/main/java/seedu/address/logic/commands/SetStatusCommand.java
Labels: alpha-bug, type.DocumentationBug

#301 Add projects to Messages
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/model/person/Person.java
Labels: priority.Medium

#306 Update UserGuide to fix constraint for add command in UserGuide
  docs/UserGuide.md
Labels: type.DocumentationBug

#307 Update developer guide with new uml diagrams
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/index.md
Labels: documentation

#309 Update Site Header
  docs/_sass/minima/_base.scss
Labels: priority.High

#391 JAR missing from glossary
  docs/DeveloperGuide.md
Labels: documentation

#394 Update User Guide - Post PE-D
  docs/UserGuide.md
Labels: documentation

#395 Dependency label not compliant with lecture
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ParserClasses.puml
Labels: type.DocumentationBug

#393 Lack of User Guide Edit Index Description
  docs/UserGuide.md
Labels: documentation

#390 Spaces allowed in name
  docs/UserGuide.md
Labels: documentation

#389 User guide has no mention of duplicate phone numbers being disallowed
  docs/UserGuide.md
Labels: documentation

#388 remediate issues from PED
  docs/UserGuide.md
Labels: documentation

#392 Incorrect description for User Guide for Edit Phone
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation
